// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notissimus_Test.Context;

namespace Notissimus_Test.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Notissimus_Test.Models.SavedOfferModel", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<bool>("Avalible")
                        .HasColumnType("bit");

                    b.Property<int>("BID")
                        .HasColumnType("int");

                    b.Property<int>("CBID")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("binding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("categoryIdID")
                        .HasColumnType("int");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_of_origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataTour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("days")
                        .HasColumnType("int");

                    b.Property<bool>("delivery")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("downloadable")
                        .HasColumnType("bit");

                    b.Property<string>("format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("hallID")
                        .HasColumnType("int");

                    b.Property<string>("hall_part")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotel_stars")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("included")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("is_kids")
                        .HasColumnType("int");

                    b.Property<int>("is_premiere")
                        .HasColumnType("int");

                    b.Property<string>("language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("local_delivery_cost")
                        .HasColumnType("float");

                    b.Property<bool>("manufacturer_warranty")
                        .HasColumnType("bit");

                    b.Property<string>("meal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("originalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("page_extent")
                        .HasColumnType("int");

                    b.Property<int>("part")
                        .HasColumnType("int");

                    b.Property<string>("performance_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("performed_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recording_length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("starring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typePrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vendorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("volume")
                        .HasColumnType("int");

                    b.Property<string>("worldRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("categoryIdID");

                    b.HasIndex("hallID");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("Notissimus_Test.Models.yml_catalogShopOfferCategoryId", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CategoryIDs");
                });

            modelBuilder.Entity("Notissimus_Test.Models.yml_catalogShopOfferHall", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("OfferHalls");
                });

            modelBuilder.Entity("Notissimus_Test.Models.SavedOfferModel", b =>
                {
                    b.HasOne("Notissimus_Test.Models.yml_catalogShopOfferCategoryId", "categoryId")
                        .WithMany()
                        .HasForeignKey("categoryIdID");

                    b.HasOne("Notissimus_Test.Models.yml_catalogShopOfferHall", "hall")
                        .WithMany()
                        .HasForeignKey("hallID");

                    b.Navigation("categoryId");

                    b.Navigation("hall");
                });
#pragma warning restore 612, 618
        }
    }
}
